function fit = fit_narx(u, y, fs, opts)
% FIT_NARX  Fit a Nonlinear ARX model — genuinely nonlinear, can capture
% arbitrary input-output relationships including harmonic generation.
%
%   fit = sysid.fit_narx(u, y, fs)
%   fit = sysid.fit_narx(u, y, fs, opts)
%
% Unlike tfest/procest (which fit linear transfer functions), NARX models
% the output as a *nonlinear function* of past inputs and outputs:
%
%     y(t) = F( y(t-1), y(t-2), ..., u(t-1), u(t-2), ... )
%
% where F is a flexible nonlinear regression (sigmoid network, tree-partition,
% wavelet network, etc.). This means it CAN, in principle, capture:
%   - Even harmonics generated by the system (our observed nonlinearity)
%   - Amplitude-dependent gain
%   - Asymmetric expansion-vs-compression response
%
% Cost: the resulting model has no clean physical interpretation (it's a
% black-box regression) and tends to overfit on small/noisy datasets.
%
% opts:
%   .na             output regressors used (default 4) — order in y
%   .nb             input regressors used  (default 4) — order in u
%   .nk             input delay in samples (default 1)
%   .nonlinearity   'sigmoidnet' (default) | 'wavenet' | 'treepartition' | 'linear'
%   .num_units      number of network units (default 10) — flexibility knob
%
% Returns:
%   .sys           idnlarx object
%   .fit_percent   MATLAB-reported training fit %
%   .opts          options used

    if nargin < 4, opts = struct(); end
    if ~isfield(opts,'na'),           opts.na = 4;           end
    if ~isfield(opts,'nb'),           opts.nb = 4;           end
    if ~isfield(opts,'nk'),           opts.nk = 1;           end
    if ~isfield(opts,'nonlinearity'), opts.nonlinearity = 'sigmoidnet'; end
    if ~isfield(opts,'num_units'),    opts.num_units = 10;   end

    Ts = 1/fs;
    data = iddata(y(:), u(:), Ts);

    switch lower(opts.nonlinearity)
        case 'sigmoidnet'
            nl = idSigmoidNetwork(opts.num_units);
        case 'wavenet'
            nl = idWaveletNetwork(opts.num_units);
        case 'treepartition'
            nl = idTreePartition;
        case 'linear'
            nl = idLinear;
        otherwise
            error('sysid:fit_narx:badNL', 'Unknown nonlinearity %s', opts.nonlinearity);
    end

    sys = nlarx(data, [opts.na opts.nb opts.nk], nl);

    fit.sys = sys;
    fit.opts = opts;
    try
        fit.fit_percent = sys.Report.Fit.FitPercent;
    catch
        fit.fit_percent = NaN;
    end
end
